import cloneDeep from 'lodash/cloneDeep'
import {Sample, Interval, Mp4BoxTree} from '../types'
import findBox from './findBox'
import getPerChunkArray from './getPerChunkArray'
import getSamplesOffset from './getSamplesOffset'